x-common-env: &common-env
  DATABASE_USER: sbomify
  DATABASE_PASSWORD: sbomify
  DATABASE_NAME: sbomify
  DATABASE_PORT: 5432
  DATABASE_HOST: localhost
  DOCKER_DATABASE_HOST: sbomify-db

x-keycloak-env: &keycloak-env
  USE_KEYCLOAK: "True"
  KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL:-http://keycloak:8080/}
  KEYCLOAK_REALM: ${KEYCLOAK_REALM:-sbomify}
  KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-sbomify}
  KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-dev-client-secret}
  KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-admin}
  KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}

services:
  sbomify-backend:
    build:
      dockerfile: docker/Dockerfile-backend-dev
    environment:
      <<: [*common-env, *keycloak-env]

  sbomify-migrations:
    build:
      dockerfile: docker/Dockerfile-backend-dev
    environment:
      <<: [*common-env, *keycloak-env]

  sbomify-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend-dev
    ports:
      - "5170:5170"
    volumes:
      - .:/code
      - /code/node_modules
    environment:
      NODE_ENV: development

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    restart: always
    environment:
      <<: *keycloak-env
      KC_HOSTNAME_URL: ${KEYCLOAK_SERVER_URL}
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

  keycloak-bootstrap:
    image: quay.io/keycloak/keycloak:26.1.4
    depends_on:
      - keycloak
    volumes:
      - ./bin/keycloak-bootstrap.sh:/keycloak-bootstrap.sh
    entrypoint: /bin/sh /keycloak-bootstrap.sh
    environment:
      <<: *keycloak-env
      KC_HOSTNAME_URL: ${KEYCLOAK_SERVER_URL}
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

volumes:
  keycloak_data:
