---
services:
  sbomify-backend:
    build:
      dockerfile: docker/Dockerfile-backend-dev
    environment:
      BILLING: False
  sbomify-migrations:
    build:
      dockerfile: docker/Dockerfile-backend-dev
    environment:
      BILLING: False
    volumes:
      - .:/code
      - /code/node_modules

  sbomify-worker:
    build:
      dockerfile: docker/Dockerfile-backend-dev
    environment:
      BILLING: False
    volumes:
      - .:/code
      - /code/node_modules
    command: dramatiq sbomify.tasks

  sbomify-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend-dev
    ports:
      - "5170:5170"
    volumes:
      - .:/code
      - /code/node_modules
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: http://127.0.0.1:8000
